<?php

/**
 * Localizations for Kolab Calendar plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/calendar/
 */

$labels = array();

// preferences
$labels['default_view'] = 'Изглед по подразбиране';
$labels['time_format'] = 'Формат на часовете';
$labels['timeslots'] = 'Деления за час';
$labels['first_day'] = 'Първи ден от седмицата';
$labels['first_hour'] = 'Първи час при показване';
$labels['workinghours'] = 'Работни часове';
$labels['add_category'] = 'Добавяне на категория';
$labels['remove_category'] = 'Премахване на категория';
$labels['defaultcalendar'] = 'Създаване на нови събития в ';
$labels['eventcoloring'] = 'Оцветяване на събитията';
$labels['coloringmode0'] = 'Според календара';
$labels['coloringmode1'] = 'Относно категорията';
$labels['coloringmode2'] = 'Календар за очертание, категория за съдържание';
$labels['coloringmode3'] = 'Категория за очертание, календар за съдържание';
$labels['afternothing'] = 'Не предприемай нищо';
$labels['aftertrash'] = 'Премести в Кошчето';
$labels['afterdelete'] = 'Изтрий съобщението';
$labels['afterflagdeleted'] = 'Маркирай като изтрито';
$labels['aftermoveto'] = 'Премести в...';
$labels['itipoptions'] = 'Покани за събитие';
$labels['afteraction'] = 'After an invitation or update message is processed';
$labels['showweekno'] = 'Display week numbers';
$labels['weeknonone'] = 'never';
$labels['weeknodatepicker'] = 'in datepicker only';
$labels['weeknoall'] = 'in datepicker and calendar view';

// calendar
$labels['calendar'] = 'Календар';
$labels['calendar_database'] = 'Database Calendar';
$labels['calendars'] = 'Календари';
$labels['category'] = 'Категория';
$labels['addcalendar'] = 'Add calendar';
$labels['categories'] = 'Категории';
$labels['createcalendar'] = 'Създаване на нов календар';
$labels['editcalendar'] = 'Edit calendar properties';
$labels['deletecalendar'] = 'Delete calendar';
$labels['name'] = 'Име';
$labels['color'] = 'Цвят';
$labels['day'] = 'Ден';
$labels['week'] = 'Седмица';
$labels['month'] = 'Месец';
$labels['agenda'] = 'Бележник';
$labels['new'] = 'Ново';
$labels['new_event'] = 'Добавяне на събитие';
$labels['edit_event'] = 'Промяна на събитие';
$labels['edit'] = 'Промяна';
$labels['save'] = 'Запис';
$labels['removelist'] = 'Премахни от списъка';
$labels['cancel'] = 'Отказ';
$labels['select'] = 'Избиране';
$labels['print'] = 'Печат';
$labels['printtitle'] = 'Печат на календарите';
$labels['title'] = 'Заглавие';
$labels['description'] = 'Описание';
$labels['all-day'] = 'цял ден';
$labels['export'] = 'Извличане';
$labels['exporttitle'] = 'Извличане към iCalendar';
$labels['exportrange'] = 'Събития от';
$labels['exportattachments'] = 'С прикачени файлове';
$labels['customdate'] = 'Дата по избор';
$labels['location'] = 'Местоположение';
$labels['url'] = 'URL адрес';
$labels['date'] = 'Дата';
$labels['start'] = 'Начало';
$labels['starttime'] = 'Време за начало';
$labels['end'] = 'Край';
$labels['endtime'] = 'Време за край';
$labels['repeat'] = 'Повтори';
$labels['selectdate'] = 'Избор на дата';
$labels['freebusy'] = 'Показване като';
$labels['free'] = 'Свободно';
$labels['busy'] = 'Заето';
$labels['outofoffice'] = 'Извън офиса';
$labels['tentative'] = 'Предварително';
$labels['mystatus'] = 'Моят статус';
$labels['status'] = 'Статус';
$labels['status-confirmed'] = 'Потвърдено';
$labels['status-cancelled'] = 'Отхвърлено';
$labels['status-tentative'] = 'Предварително';
$labels['priority'] = 'Приоритет';
$labels['sensitivity'] = 'Поверителност';
$labels['public'] = 'публично';
$labels['private'] = 'частно';
$labels['confidential'] = 'конфиденциално';
$labels['links'] = 'Цикличност';
$labels['alarms'] = 'Напомняне';
$labels['comment'] = 'Коментар';
$labels['created'] = 'Създаден';
$labels['changed'] = 'Последна промяна';
$labels['unknown'] = 'Неизвестно';
$labels['eventoptions'] = 'Опции';
$labels['generated'] = 'генерирано в';
$labels['eventhistory'] = 'История';
$labels['removelink'] = 'Премахни е-мейл препратките';
$labels['printdescriptions'] = 'Печат на описанията';
$labels['parentcalendar'] = 'Внасяне вътре';
$labels['searchearlierdates'] = '« Търсене за по- стари събития';
$labels['searchlaterdates'] = 'Търсене за по- нови събития »';
$labels['andnmore'] = '$nr повече...';
$labels['togglerole'] = 'Натиснете за превключване на роля';
$labels['createfrommail'] = 'Запазване като събитие';
$labels['importevents'] = 'Внасяне на събития';
$labels['importrange'] = 'Събития от';
$labels['onemonthback'] = '1 месец назад';
$labels['nmonthsback'] = '$nr месеца назад';
$labels['showurl'] = 'Показване на URL на календара';
$labels['showurldescription'] = 'Използвайте следния адрес, за да достъпвате (само за четене) вашия календар от други приложения. Можете да копирате и поставяте това във всеки календарен софтуер, поддържащ форматът iCal';
$labels['caldavurldescription'] = 'Copy this address to a <a href="http://en.wikipedia.org/wiki/CalDAV" target="_blank">CalDAV</a> client application (e.g. Evolution or Mozilla Thunderbird) to fully synchronize this specific calendar with your computer or mobile device.';
$labels['findcalendars'] = 'Find calendars...';
$labels['searchterms'] = 'Search terms';
$labels['calsearchresults'] = 'Available Calendars';
$labels['calendarsubscribe'] = 'Постоянен списък';
$labels['nocalendarsfound'] = 'Не бяха намерени календари';
$labels['nrcalendarsfound'] = 'Бяха намерени $nr календара';
$labels['quickview'] = 'Покажи само този календар';
$labels['invitationspending'] = 'Чакащи покани';
$labels['invitationsdeclined'] = 'Отхвърлени покани';
$labels['changepartstat'] = 'Промени състоянието на участник';
$labels['rsvpcomment'] = 'Текст на поканата';

// agenda view
$labels['listrange'] = 'Оразмеряване към екран:';
$labels['listsections'] = 'Разделяне на:';
$labels['smartsections'] = 'Интелигентни секции';
$labels['until'] = 'до';
$labels['today'] = 'Днес';
$labels['tomorrow'] = 'Утре';
$labels['thisweek'] = 'Тази седмица';
$labels['nextweek'] = 'Следващата седмица';
$labels['prevweek'] = 'Миналата седмица';
$labels['thismonth'] = 'Този месец';
$labels['nextmonth'] = 'Следващия месец';
$labels['weekofyear'] = 'Седмица';
$labels['pastevents'] = 'Минали';
$labels['futureevents'] = 'Бъдещи';

// alarm/reminder settings
$labels['showalarms'] = 'Покажи напомняния';
$labels['defaultalarmtype'] = 'Настройка за напомняне по подразбиране';
$labels['defaultalarmoffset'] = 'Време за напомняне по подразбиране';
//$labels['alarmdisplayoption'] = 'Default Reminder';

// attendees
$labels['attendee'] = 'Участник';
$labels['role'] = 'Роля';
$labels['availability'] = 'Налич.';
$labels['confirmstate'] = 'Статус';
$labels['addattendee'] = 'Добавяне на участник';
$labels['roleorganizer'] = 'Организатор';
$labels['rolerequired'] = 'Задължителен';
$labels['roleoptional'] = 'По избор';
$labels['rolechair'] = 'Председател';
$labels['rolenonparticipant'] = 'Липсващ';
$labels['cutypeindividual'] = 'Индивидуален';
$labels['cutypegroup'] = 'Група';
$labels['cutyperesource'] = 'Ресурс';
$labels['cutyperoom'] = 'Стая';
$labels['availfree'] = 'Свободен';
$labels['availbusy'] = 'Зает';
$labels['availunknown'] = 'Няма информация';
$labels['availtentative'] = 'Предварително';
$labels['availoutofoffice'] = 'Извън офиса';
$labels['delegatedto'] = 'Delegated to: ';
$labels['delegatedfrom'] = 'Delegated from: ';
$labels['scheduletime'] = 'Find availability';
$labels['sendinvitations'] = 'Изпращане на покани';
$labels['sendnotifications'] = 'Известяване на участниците относно промените';
$labels['sendcancellation'] = 'Известяване на участниците относно отмяна на събития';
$labels['onlyworkinghours'] = 'Find availability within my working hours';
$labels['reqallattendees'] = 'Required/all participants';
$labels['prevslot'] = 'Previous Slot';
$labels['nextslot'] = 'Next Slot';
$labels['suggestedslot'] = 'Suggested Slot';
$labels['noslotfound'] = 'Unable to find a free time slot';
$labels['invitationsubject'] = 'Бяхте поканен на "$title"';
$labels['invitationmailbody'] = "*\$title*\n\nWhen: \$date\n\nInvitees: \$attendees\n\nPlease find attached an iCalendar file with all the event details which you can import to your calendar application.";
$labels['invitationattendlinks'] = "In case your email client doesn't support iTip requests you can use the following link to either accept or decline this invitation:\n\$url";
$labels['eventupdatesubject'] = '"$title" has been updated';
$labels['eventupdatesubjectempty'] = '"$title" беше отмнено';
$labels['eventupdatemailbody'] = "*\$title*\n\nWhen: \$date\n\nInvitees: \$attendees\n\nPlease find attached an iCalendar file with the updated event details which you can import to your calendar application.";
$labels['eventcancelsubject'] = '"$title" has been canceled';
$labels['eventcancelmailbody'] = "*\$title*\n\nWhen: \$date\n\nInvitees: \$attendees\n\nThe event has been cancelled by \$organizer.\n\nPlease find attached an iCalendar file with the updated event details.";

// invitation handling (overrides labels from libcalendaring)
$labels['itipobjectnotfound'] = 'The event referred by this message was not found in your calendar.';
$labels['itipmailbodyaccepted'] = "\$sender has accepted the invitation to the following event:\n\n*\$title*\n\nWhen: \$date\n\nInvitees: \$attendees";
$labels['itipmailbodytentative'] = "\$sender has tentatively accepted the invitation to the following event:\n\n*\$title*\n\nWhen: \$date\n\nInvitees: \$attendees";
$labels['itipmailbodydeclined'] = "\$sender has declined the invitation to the following event:\n\n*\$title*\n\nWhen: \$date\n\nInvitees: \$attendees";
$labels['itipmailbodycancel'] = "\$sender has rejected your participation in the following event:\n\n*\$title*\n\nWhen: \$date";
$labels['itipmailbodydelegated'] = "\$sender has delegated the participation in the following event:\n\n*\$title*\n\nWhen: \$date";
$labels['itipmailbodydelegatedto'] = "\$sender has delegated the participation in the following event to you:\n\n*\$title*\n\nWhen: \$date";

$labels['itipdeclineevent'] = 'Искате ли да отхвърлите поканата за това събитие?';
$labels['declinedeleteconfirm'] = 'Do you also want to delete this declined event from your calendar?';
$labels['itipcomment'] = 'Invitation/notification comment';
$labels['itipcommenttitle'] = 'This comment will be attached to the invitation/notification message sent to participants';

$labels['notanattendee'] = 'You\'re not listed as an attendee of this event';
$labels['eventcancelled'] = 'The event has been cancelled';
$labels['saveincalendar'] = 'запазване в';
$labels['updatemycopy'] = 'Обнови в моя календар';
$labels['savetocalendar'] = 'Запази в календар';
$labels['openpreview'] = 'Провери календар';
$labels['noearlierevents'] = 'Няма по-ранни събития';
$labels['nolaterevents'] = 'Няма по-късни събития';

// resources
$labels['resource'] = 'Ресурс';
$labels['addresource'] = 'Book resource';
$labels['findresources'] = 'Find resources';
$labels['resourcedetails'] = 'Детайли';
$labels['resourceavailability'] = 'Availability';
$labels['resourceowner'] = 'Собственик';
$labels['resourceadded'] = 'The resource was added to your event';

// event dialog tabs
$labels['tabsummary'] = 'Заглавие';
$labels['tabrecurrence'] = 'Да се повтаря';
$labels['tabattendees'] = 'Участници';
$labels['tabresources'] = 'Ресурси';
$labels['tabattachments'] = 'Прикрепени файлове';
$labels['tabsharing'] = 'Споделяне';

// messages
$labels['deleteobjectconfirm'] = 'Наистина ли искате да премахнете това събитие?';
$labels['deleteventconfirm'] = 'Наистина ли искате да премахнете това събитие?';
$labels['deletecalendarconfirm'] = 'Наистина ли искате да премахнете този календар с всичките му събития?';
$labels['deletecalendarconfirmrecursive'] = 'Наистина ли искате да премахнете този календар с всичките му събития и допълнителни календари?';
$labels['savingdata'] = 'Запазване на данни...';
$labels['errorsaving'] = 'Неуспешно записването на промените.';
$labels['operationfailed'] = 'The requested operation failed.';
$labels['invalideventdates'] = 'Invalid dates entered! Please check your input.';
$labels['invalidcalendarproperties'] = 'Invalid calendar properties! Please set a valid name.';
$labels['searchnoresults'] = 'No events found in the selected calendars.';
$labels['successremoval'] = 'Събитието беше премахнато успешно.';
$labels['successrestore'] = 'Събитието беше възстановено успешно.';
$labels['errornotifying'] = 'Failed to send notifications to event participants';
$labels['errorimportingevent'] = 'Failed to import the event';
$labels['importwarningexists'] = 'A copy of this event already exists in your calendar.';
$labels['newerversionexists'] = 'A newer version of this event already exists! Aborted.';
$labels['nowritecalendarfound'] = 'No calendar found to save the event';
$labels['importedsuccessfully'] = 'Събитието е добавено успешно към \'$calendar\'';
$labels['updatedsuccessfully'] = 'Събитието беше обновено успешно в \'$calendar\'';
$labels['attendeupdateesuccess'] = 'Successfully updated the participant\'s status';
$labels['itipsendsuccess'] = 'Invitation sent to participants.';
$labels['itipresponseerror'] = 'Failed to send the response to this event invitation';
$labels['itipinvalidrequest'] = 'This invitation is no longer valid';
$labels['sentresponseto'] = 'Successfully sent invitation response to $mailto';
$labels['localchangeswarning'] = 'You are about to make changes that will only be reflected on your calendar and not be sent to the organizer of the event.';
$labels['importsuccess'] = '$nr събития бяха внесени успешно.';
$labels['importnone'] = 'Не бяха намерени събития за внасяне';
$labels['importerror'] = 'Възникна грешка при внасянето на събития';
$labels['aclnorights'] = 'Не разполагате с административни права върху този календар.';

$labels['changeeventconfirm'] = 'Промяна на събитие';
$labels['removeeventconfirm'] = 'Изтриване на събитие';
$labels['changerecurringeventwarning'] = 'This is a recurring event. Would you like to edit the current event only, this and all future occurences, all occurences or save it as a new event?';
$labels['removerecurringeventwarning'] = 'This is a recurring event. Would you like to delete the current event only, this and all future occurences or all occurences of this event?';
$labels['removerecurringallonly'] = 'This is a recurring event. As a participant, you can only delete the entire event with all occurences.';
$labels['currentevent'] = 'Настоящи';
$labels['futurevents'] = 'Бъдещи';
$labels['allevents'] = 'Всички';
$labels['saveasnew'] = 'Запази като нов';

// birthdays calendar
$labels['birthdays'] = 'Рождени дни';
$labels['birthdayscalendar'] = 'Birthdays Calendar';
$labels['displaybirthdayscalendar'] = 'Display birthdays calendar';
$labels['birthdayscalendarsources'] = 'From these address books';
$labels['birthdayeventtitle'] = '$name\'s Birthday';
$labels['birthdayage'] = 'Age $age';

// history dialog
$labels['objectchangelog'] = 'Change History';
$labels['objectdiff'] = 'Changes from $rev1 to $rev2';
$labels['revision'] = 'Revision';
$labels['user'] = 'User';
$labels['operation'] = 'Action';
$labels['actionappend'] = 'Saved';
$labels['actionmove'] = 'Moved';
$labels['actiondelete'] = 'Deleted';
$labels['compare'] = 'Compare';
$labels['showrevision'] = 'Show this version';
$labels['restore'] = 'Restore this version';
$labels['objectnotfound'] = 'Failed to load event data';
$labels['objectchangelognotavailable'] = 'Change history is not available for this event';
$labels['objectdiffnotavailable'] = 'No comparison possible for the selected revisions';
$labels['revisionrestoreconfirm'] = 'Do you really want to restore revision $rev of this event? This will replace the current event with the old version.';
$labels['objectrestoresuccess'] = 'Revision $rev successfully restored';
$labels['objectrestoreerror'] = 'Failed to restore the old revision';


// (hidden) titles and labels for accessibility annotations
$labels['arialabelminical'] = 'Calendar date selection';
$labels['arialabelcalendarview'] = 'Преглед на календара';
$labels['arialabelsearchform'] = 'Event search form';
$labels['arialabelquicksearchbox'] = 'Event search input';
$labels['arialabelcalsearchform'] = 'Calendars search form';
$labels['calendaractions'] = 'Calendar actions';
$labels['arialabeleventattendees'] = 'Списък с участниците в събитието';
$labels['arialabeleventresources'] = 'Event resources list';
$labels['arialabelresourcesearchform'] = 'Resources search form';
$labels['arialabelresourceselection'] = 'Налични ресурси';

$labels['calendar_kolab'] = 'Kolab Calender';
$labels['calendar_caldav'] = 'CalDAV Calender';
$labels['calendar_ical'] = 'iCAL Calender';
$labels['calendar_google'] = 'Google Calender';

$labels['caldav_url'] = 'CalDAV URL';
$labels['caldav_auth_digest'] = 'CalDAV Digest Login';
$labels['caldav_auth_oauth'] = 'CalDAV OAuth2 Login';

$labels['ical_url'] = 'iCal URL';
$labels['ical_auth_digest'] = 'iCal Basic Auth Login';

$labels['auth'] = 'Authentication';
$labels['login_with'] = 'Login with ';
$labels['logout_from'] = 'Logout from ';
?>
